image: docker:20.10.16-dind

services:
  - docker:dind

stages:
  - dependency-build
  - package-deploy

install_dependency-build:
  image: amazoncorretto:17-alpine-jdk
  stage: dependency-build
  script:
    - echo "Instalação de dependências..."
    - apk update
    - apk add --update nodejs
    - apk add --update npm
    - npm install
    - npm install -g @angular/cli@17
    - npm install -g http-server
    - echo "Build da aplicação..."
    - ng build

  artifacts:
    paths:
      - dist/
  only:
    - develop

package-deploy:
  stage: package-deploy
  script:
    - echo "Criando a imagem Docker..."
    - docker build . -t "$DOCKERHUB_IMAGE_DEV"
    - echo "Mostrando lista de images..."
    - docker images
    - echo "Fazendo o deploy para o Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_IMAGE_DEV"
  only:
    - develop
