image: docker:20.10.16-dind

services:
  - docker:dind

stages:
  - dependency-build
  - package-deploy

install_dependency-build:
  image: amazoncorretto:17-alpine-jdk
  stage: dependency-build
  script:
    - echo "Instalação de dependências..."
    - apk update
    - apk add --update npm
    - npm install -g @angular/cli@17
    - npm install
    - echo "Build da aplicação..."
    - ng build

  artifacts:
    paths:
      - dist/
  only:
    - main

package-deploy:
  stage: package-deploy
  script:
    - echo "Criando a imagem Docker..."
    - docker build . --platform linux/arm64 -t "$DOCKERHUB_IMAGE_PROD"
    - echo "Mostrando lista de images..."
    - docker images
    - echo "Fazendo o deploy para o Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push "$DOCKERHUB_IMAGE_PROD"
  only:
    - main
